apiVersion: v1
kind: Deployment
metadata:
   name: deployment1
   labels: 
    app: project

spec:
  replicas: 4 
  selector:
     matchLabels: 
        app: project
  template:
     metadata:
        Labels:
          app: project
     spec: 
        container: 
        - name: project
          image: chandana1213/myimg01:latest
          ports:
          - containerPort: 8000
  
   
   
